# Generated by Django 3.2.9 on 2021-11-20 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('childProblemApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='storage/images')),
                ('studyLevel', models.CharField(choices=[('1ST', 'First Year'), ('2ND', 'Second Year')], default='1ST', max_length=3)),
            ],
            options={
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='ChildPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childProblemApp.child')),
            ],
            options={
                'db_table': 'child_place',
            },
        ),
        migrations.DeleteModel(
            name='Emplacement',
        ),
        migrations.RemoveField(
            model_name='enfant',
            name='Parent',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Rapport',
        ),
        migrations.DeleteModel(
            name='Tache',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='date_naissance',
            new_name='birthDate',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='prenom',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Enfant',
        ),
        migrations.RemoveField(
            model_name='place',
            name='attitude',
        ),
        migrations.AddField(
            model_name='place',
            name='lattitude',
            field=models.DecimalField(decimal_places=6, default=38.8951, max_digits=9),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=-77.0364, max_digits=9),
        ),
        migrations.AlterModelTable(
            name='parent',
            table='parent',
        ),
        migrations.AlterModelTable(
            name='place',
            table='place',
        ),
        migrations.DeleteModel(
            name='Enfant',
        ),
        migrations.AddField(
            model_name='childplace',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childProblemApp.place'),
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='childProblemApp.parent'),
        ),
        migrations.AddField(
            model_name='place',
            name='children',
            field=models.ManyToManyField(through='childProblemApp.ChildPlace', to='childProblemApp.Child'),
        ),
    ]
