# Generated by Django 3.2.9 on 2021-11-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('childProblemApp', '0002_auto_20211120_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('RESTING', 'pause'), ('CLEANING', 'ménage'), ('STUDYING', 'homework'), ('PLAYING', 'jouer'), ('READING', 'lire un livre')], default='RESTING', max_length=10)),
            ],
        ),
    ]
