# Generated by Django 3.2.9 on 2021-11-21 10:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('childProblemApp', '0003_mission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('note', models.CharField(choices=[('TRAFFIC', 'emboutillage'), ('KEEP', ' peut garder les enfants 15 minutes après la séance')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('messsage_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=500)),
                ('problems', models.CharField(blank=True, max_length=500, null=True)),
                ('profits', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='childProblemApp.mission'),
        ),
        migrations.AddField(
            model_name='child',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='childProblemApp.message'),
        ),
        migrations.AddField(
            model_name='mission',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='childProblemApp.location'),
        ),
        migrations.AddField(
            model_name='mission',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='childProblemApp.report'),
        ),
    ]
